[package]
name = "elune"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.12", features = ["tokio", "canvas"] }
sysinfo = "0.30"
chrono = "0.4"
tray-icon = "0.11"
window-shadows = "0.2"

